### PR TITLE
name specifier detected on insert node (not a patch)

### PR DESCRIPTION
**Pull request by Gordon-Dry**

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
btw
https://forum.kerbalspaceprogram.com/index.php?/topic/167450-14x-15x-textures-unlimited-pbr-shader-texture-set-and-model-loading-api/&do=findComment&comment=3486530

**Comment by linuxgurugamer** [comment]
Based on that link, it seems that it can just be removed entirely, right?

**Comment by Gordon-Dry** [comment]
Yes.

I always wondered (the last months) why so many mods have this, when it's in the main TU default config ...

**Comment by linuxgurugamer** [comment]
I decided to just comment the whole thing out for now, I added your chagnes by hand first.  Thanks

**Pull request closed without merging**
